### ISSUE TITLE
invalid url tests aren't actually invalid

### ISSUE THREAD

**Issue by mattgarrish** [w3c/publ-tests#12]
One problem I found running the manifest processing tests is that the invalid URLs don't register as invalid per the javascript URL api. I fiddled with the tests to make the URLs fail to ensure the right result, but just looked at the URL standard and a percent in the pathname is not invalid anymore, which is what it is following (browsers still choke on the percent, but that's another story, I guess).

By the [percent encoded bytes section](https://url.spec.whatwg.org/#percent-encoded-bytes), if a percent character isn't followed by two hex characters, the percent is dropped during parsing and the following two characters retained.

If you put a [percent in the host](https://url.spec.whatwg.org/#host-miscellaneous), however, you will get an invalid URL.

I'm not sure what can go in a relative path to break the conversion, though. I tried some of the problematic patterns in the standard, but the api just wipes out the invalid parts and returns a URL.

**Comment by iherman** [comment]
@mattgarrish which of our tests are affected by this?

**Comment by mattgarrish** [comment]
Don't have the numbers handy, but if you search the json file for "invalid url" you'll find them.

As I said, I don't know what would make for a usable alternative other than to not use relative paths and make the domain and/or scheme invalid. But maybe other libraries will still report these as invalid; could just be the javascript API is more flexible to the URL spec.

**Comment by iherman** [comment]
I would propose not to touch this for now. Let us see if other testers come up with issues...

**Comment by marisademeglio** [comment]
I'm finding the same as @mattgarrish - the API in the browser does not find these to be invalid, so my implementation fails all the URL tests. I could stop relying on the built-in URL methods and use a custom regex, but I'm not really inclined to... 

I did some experiments with [valid-url](https://www.npmjs.com/package/valid-url) and it reports them as invalid, but as I'm not using Node, it's not of much use to me.

**Comment by iherman** [comment]
Yep, I my stuff is on top of Node, hence I did not even realize the problem.

I would still think that we could/should leave the test as is, although we may want to add some remark in the json index.

**Comment by mattgarrish** [comment]
> I would still think that we could/should leave the test as is

Or should we omit the tests for now?

Technically, Marisa and I should be reporting that we failed the tests, even though the outcome we got is consistent with the URL spec.

**Comment by iherman** [comment]
Is there really no way of creating a URL that _does_ report an error? 

The tests should prove that the implementation does have a branch of testing that stuff. I understand that the outcome will depend on the underlying library but if we do not have a test then implementations may be tempted to avoid testing altogether...

**Comment by mattgarrish** [comment]
Absolute URLs can be made invalid easily enough by manipulating the scheme/domain. Any of these will be reported as invalid:

http:example.com
http://ex%mple.com/
http://ex  mple.com/

Was there a need for the tests to use relative URLs?

**Comment by iherman** [comment]
Here are the tests where we do use invalid URLs: 

- publication_manifest/manifest_processing/tests/m4.7.1.3.03.jsonld
- publication_manifest/manifest_processing/tests/m4.7.2.1.02.jsonld
- publication_manifest/manifest_processing/tests/m4.7.2.2.02.jsonld
- publication_manifest/manifest_processing/tests/m4.7.2.3.02.jsonld
- publication_manifest/manifest_processing/tests/m4.7.1.4.01.jsonld

Only the first one uses an invalid relative URLs as a possible value for the 'url' term. That can be absolute. All others are absolute.

**Comment by mattgarrish** [comment]
Finally found a minute to look at these again. So, ya, I think the one in 4.7.1.3.03 was the one that confused me, as it was an array of relative addresses. But no reason we can't put an absolute in just for testing purposes.

The one in 4.7.1.4.01 for the id can just be flipped to an invalid absolute url, just like the other three. I'll open a pr for these shortly.

It just leaves us without any tests for invalid relative paths, which was the bigger issue. I guess we just live without for now given the discrepancies in how they're handled.
