### ISSUE TITLE
Inconsistent test file naming

### ISSUE THREAD

**Issue by marisademeglio** [w3c/publ-tests#18]
Among the three testsuites, "publication manifest processing" and "audiobooks manifest processing" test files are named after the test ID, prefixed with `test_`, but those in the "toc processing" testsuite are not prefixed.

E.g. 

https://github.com/w3c/publ-tests/blob/master/publication_manifest/manifest_processing/tests/index.json#L11

seems to mean that testers should use the file `test_m4.01.jsonld`

vs

https://github.com/w3c/publ-tests/blob/master/publication_manifest/toc_processing/tests/index.json#L13

points to `s4.8.1.3.01.html`, not `test_s4.8.1.3.01.html`.

I care because I have written something to help me step through each testsuite and record the results of my audiobooks parsing library:

https://marisademeglio.github.io/audiobooks-js/official-tests/

It would be nice if the `index.json` id reference/test file name correlation was consistent.

**Comment by iherman** [comment]
@mattgarrish you created those tests... is it o.k. to change that?

I had the same problem as @marisademeglio: the script I used to run the tests had to have some extra logic to differentiate between TOC tests and the others. (That being said, if we change that, I will have to change my test runner, but I am happy to do that if it makes the life easier for all the testers.)

**Comment by mattgarrish** [comment]
Is there any reason to prefix the tests and make them differ from the IDs? That's probably why I didn't do it, as it just adds an undocumented step to running the tests.

But if you want to go the other way it doesn't matter to me.

**Comment by iherman** [comment]
Probably no reason at all... the real problem of @marisademeglio is a lack of consistency.

Should we flip a coin which one we change? Actually, I believe changing the TOC tests may be easier because there are less of those...:-)

**Comment by mattgarrish** [comment]
I can run a shell script that'll flip them either way, which is why I'm not that strongly invested.

Flip that coin and tell me which you prefer!

**Comment by marisademeglio** [comment]
I don't have strong feelings about it but I can say my first instinct was to look for a test file with the same name as the ID, with no prefix.

Also, while we're at it, what is the 'format' property for ? On a few tests in the index file, I see it listed.

**Comment by mattgarrish** [comment]
> Also, while we're at it, what is the 'format' property for ? On a few tests in the index file, I see it listed

Not 100% sure, but looks like a precursor to the media-type attribute.

**Comment by iherman** [comment]
>> Also, while we're at it, what is the 'format' property for ? On a few tests in the index file, I see it listed
>
> Not 100% sure, but looks like a precursor to the media-type attribute.

That is correct. We can remove it, though it does not do any harm:-)
