### ISSUE TITLE
Test causes error but says no errors are expected

### ISSUE THREAD

**Issue by marisademeglio** [w3c/publ-tests#19]
For test [m4.7.2.3.01](https://w3c.github.io/publ-tests/publication_manifest/manifest_processing/tests/test_m4.7.2.3.01.jsonld), a conformant processor reports a validation error because the link has no `rel` property. See manifest data validation step [12.c](https://www.w3.org/TR/pub-manifest/#links-check-rel-exists).

Because the error is not related to what the test is testing, I would say the test still passes, but technically, the expected output is different, so the test does seem a bit flawed.

Note that this is also true for several of the other `links` tests.

**Comment by iherman** [comment]
@marisademeglio  you are absolutely right. See PR #20.

I have changed the description of the test. For the others, I have changed the tests themselves by adding a dummy rel value.
