### ISSUE TITLE
Test m4.6.03 raises errors related to audiobooks requirements

### ISSUE THREAD

**Issue by marisademeglio** [w3c/publ-tests#28]
In the publication manifest testsuite, test `m4.6.03` does not say to expect any errors, but because the test file is an audiobooks manifest, it raises several validation errors related to [this requirement about recommended properties](https://www.w3.org/TR/audiobooks/#validate-rec-properties)

**Comment by iherman** [comment]
@marisademeglio you are right. This should indeed raise audiobook specific errors; this is exactly the point of the test (recognizing a specific profile).

Adjusted the test manifest.

**Comment by mattgarrish** [comment]
Ya, I suspect this one slipped by me as I hadn't implemented audiobook support at the time and was treating everything as pub manifest.
