### ISSUE TITLE
Test m4.7.2.1.02 says it should cause two errors

### ISSUE THREAD

**Issue by marisademeglio** [w3c/publ-tests#29]
Test `m4.7.2.1.02` in the publication manifest testsuite says it should cause two errors. Where in the spec/processing algorithm does it indicate that this should raise two errors instead of one?

**Comment by iherman** [comment]
There are two error conditions (illegal URL and no resource in the reading order). None of them are defined as fatal error, ie, the processing goes on after the first error to detect all the others...

**Comment by marisademeglio** [comment]
I now see how expecting two errors is correct. However, isn't an empty reading order a fatal condition?

From https://www.w3.org/TR/pub-manifest/#default-reading-order:
>The default reading order MUST include at least one resource after processing of the manifest.

And in the processing algorithm, https://www.w3.org/TR/pub-manifest/#processing-defaults-reading-order (paraphrased below):

1. "Remove empty arrays", which would remove the reading order property if it were empty
2. If the reading order is not set, and there is no document URL, this is a fatal error.

I would expect the test behavior to be 

1. validation error on illegal URL
2. fatal error on no reading order

**Comment by marisademeglio** [comment]
That makes sense now, thanks!
