### ISSUE TITLE
Different rules for resources vs readingOrder duplicate URLs

### ISSUE THREAD

**Issue by marisademeglio** [w3c/publ-tests#30]
In the publication manifest testsuite: 
* `m4.7.2.1.04` indicates to warn on duplicate URLs in reading order, but do not remove them.
* `m4.7.2.2.03` indicates to warn on duplicate URLs in resources, and then remove them. 

Where in the spec does it make this distinction? Both sections say SHOULD NOT include duplicates but I can't find where it says to remove them in the reading order, and leave them in resources.

**Comment by iherman** [comment]
I guess because the first one refers to the reading order but the other is 'just' a duplication in the resources. I would leave this to @mattgarrish ...

**Comment by mattgarrish** [comment]
Looks like we missed these tests when we changed the spec to allow fragment identifiers. It used to be that duplicates were removed, but now we only do that to generate the uniqueResources list.

**Comment by marisademeglio** [comment]
Ok, so the requirement is to warn on duplicates in both resources and readingOrder, and to not remove in either case?

And, for example, these are duplicates:

* chapter1.html
* chapter1.html#section3

 ?

**Comment by mattgarrish** [comment]
> Ok, so the requirement is to warn on duplicates in both resources and readingOrder, and to not remove in either case?

Right, that's what the result should be.

> And, for example, these are duplicates:
> 
>     * chapter1.html
> 
>     * chapter1.html#section3

Yep. The [get unique urls function](https://w3c.github.io/pub-manifest/#dfn-get-unique-urls) checks for duplicates within each of these lists by parsing out the fragments and issues the validation error(s).

**Comment by marisademeglio** [comment]
I see that it says this about duplicate URLs:

1. from https://www.w3.org/TR/pub-manifest/#default-reading-order
> Resources SHOULD NOT be listed more than once in the reading order, as this can lead to
> unexpected results in user agents (e.g., links to the resource might not resolve to the right
> instance in the reading order).

2. from https://www.w3.org/TR/pub-manifest/#resource-list
> To avoid conflicting information about a resource, a particular resource's URL SHOULD NOT be 
> repeated within the resource list.

> The URLs expressed in the resource list SHOULD NOT include fragment identifiers.

But where in the processing algorithm does it talk about validation errors for duplicates, as determined by `get unique URLs`? Sorry if I'm missing something.

I would have expected to see it here: 
https://www.w3.org/TR/pub-manifest/#global-linkedresource

The only step I see that references `get unique URLs` is here:
https://www.w3.org/TR/pub-manifest/#validate-unique-resources

and it doesn't mention validation errors on duplicates, it just describes how to calculate `uniqueResources`. 

Also, are processing agents expected to issue validation errors when there are fragments in resource list URLs, as mentioned in https://www.w3.org/TR/pub-manifest/#resource-list ?

**Comment by mattgarrish** [comment]
Step b raises the validation error:

> if uniqueURLs contains url, validation error. Otherwise, append url to uniqueURLs.

This function gets called for each of readingOrder and resources as part of creating the uniqueURLs list in [step 11](https://w3c.github.io/pub-manifest/#validate-unique-resources) of the data validation steps.

**Comment by marisademeglio** [comment]
That makes sense, thanks!

**Comment by mattgarrish** [comment]
Might be useful to more explicitly note that this checking is occurring in the explanation for step 11, as it only mentions getting the list of unique urls.  wdyt @iherman ?

**Comment by iherman** [comment]
I have created a PR #34 to change the test description.  @mattgarrish I would prefer you make the editorial change on the spec...
