### ISSUE TITLE
What does "flagged" mean, with respect to manifest processing?

### ISSUE THREAD

**Issue by marisademeglio** [w3c/publ-tests#31]
In the publication manifest testsuite, several tests indicate that the offending item should be flagged. I can certainly interpret this loosely but as the processing algorithm is quite specific, down to the different types of errors, it's odd that there is no definition of "flagged".  Should it generate its own error that specifically mentions it by, say, URL? Or should the expected error include enough information to identify the offending item?

Here are the relevant tests:

* m4.8.1.1.01
* m4.8.1.2.01
* m4.8.1.3.01
* m4.8.1.3.02

**Comment by iherman** [comment]
@mattgarrish ?

**Comment by mattgarrish** [comment]
IDK. The "actions" field seems kind of redundant in these cases. The "description" identifies the nature of the test and "errors" notes that each results in a validation error.

We could change "should be flagged" with "generates a validation error" just to keep the language consistent.

**Comment by iherman** [comment]
Ah. This is simply then the sloppiness of yours truly. (I added those descriptions on the fly while creating the first batch of tests to debug my implementations and the subsequent clean-up of the descriptions was sloppy...)

My apologies. There is now a PR #35 for those.
