### ISSUE TITLE
Audiobooks tests: why test that an empty manifest gets returned?

### ISSUE THREAD

**Issue by marisademeglio** [w3c/publ-tests#32]
In the audiobooks testsuite, test `a5.6.01` says to return an empty manifest and a fatal errors. 

Where in the spec does it indicate that an empty manifest should be returned in this particular case?

**Comment by iherman** [comment]
Any fatal error means an empty manifest is returned. In this case the reading order is empty, which is a fatal error.

@mattgarrish ?

**Comment by mattgarrish** [comment]
Technically, all the specification say is to return failure in these cases. I suspect that's what Marisa is getting at. We don't say whether to return an empty manifest, null or nothing at all, as how the user agent handles the failure is outside the scope of the algorithm.

**Comment by iherman** [comment]
Ah. So the test manifest formulation should be made more precise, ie, not requiring that an empty manifest is returned. (My implementation does that...).

**Comment by mattgarrish** [comment]
Right, I think all we need to say is that the tests results in a fatal error and leave the meaning of that to implementers. Its definition makes it terminating.

**Comment by iherman** [comment]
@mattgarrish will you come up with a PR on this one? I do not want both of us to do the same work... :-)
